language: java

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.zinc

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version
  # Workaround to avoid build timeout
  # (maybe it's not required anymore when using build matrix)
  # - mvn compile -Ptravis --fail-never --update-snapshots --settings .travis.settings.xml -e
  # - mvn test-compile -Ptravis --fail-never --update-snapshots --settings .travis.settings.xml -e

env:
  matrix:
    # Travis starts only 5 concurrent processes. Most important (recent) subdirs placed first to build them first.
    - SUBDIR="reporting"
    - SUBDIR="play26"
    - SUBDIR="play25"
    - SUBDIR="play24"
    - SUBDIR="play23"
    - SUBDIR="play22"
    - SUBDIR="play21"
    # - SUBDIR="activator"

script:
  - mvn verify --file $SUBDIR/pom.xml -Ptravis --update-snapshots --settings .travis.settings.xml -e

jdk: oraclejdk8
